version: '3.4'

services:
  activity:
    image: '${DOCKER_REGISTRY}activity-api'
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - MongoDB__hosts=mongo:27017
      - MongoDB__database=testbank
  mongo:
    image: mongo:4.1
    ports:
      - 27017:27017