version: '3.4'

services:
  activity:
    build: .
    image: 'activity-api:${TAG}'
    ports:
      - 5000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      
networks:
  default:
    external:
      name: local_bridge
